### PR TITLE
Support multiple attachments on Android

### LINKED ISSUE #153: After Recent Multiple Attachment Update No Files Attach
Pulled down the recent master updates featuring the updated multiple attachment support. However I cannot get any attachments to work. Here's my config:

```
		Mailer.mail(
			{
				subject: 'Document',
				recipients: [ 'office@company.com' ],
				body: '<b>Document attached:</b>',
				isHTML: true,
				attachments: [
					{
						path: attachmentPathCsv,
						type: 'csv' // Mime Type: jpg, png, doc, ppt, html, pdf, csv
					},
					{	
						path: attachmentPath,
						type: 'pdf'
					}
				]
			},
			(error, event) => {
				Alert.alert(
					error,
					event,
					[
						{ text: 'Ok', onPress: () => console.log('OK: Email Error Response') },
						{ text: 'Cancel', onPress: () => console.log('CANCEL: Email Error Response') }
					],
					{ cancelable: true }
				);
			}
		);
```

### PR DESCRIPTION
**Pull request by grit96**
Fixes #153.

I've tested this in my app using my [patch](https://gist.github.com/grit96/3ec60fd657af831c8a5c61f9dd78c43a) via `patch-package` but haven't tested it properly standalone.

It uses `FileProvider` so might need to include some of #127.

Please can someone else test it too to make sure there's nothing else missing in this implementation?

### CODE REVIEW

**Comment by chirag04** [comment]
@Relax594

**Comment by Relax594** [comment]
Instant crash on first run
`Couldn't find meta-data for provider with authority de...`

what am i missing?

**Comment by grit96** [comment]
I've implemented the FileProvider the way https://github.com/react-native-community/react-native-share does it so it will work if the app has its own FileProvider implementation (otherwise the manifest merger will fail on build).

**Comment by Relax594** [comment]
Even better, good catch. 

The only thing im not quite sure about is
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

Shouldn't this be up to the user instead of having it inside the lib?

**Comment by grit96** [comment]
True, I only added it to mimic RNShare's implementation - I assume it would work without it?

**Comment by Relax594** [comment]
It does. If the user needs it however, its up to him to add this into the app's manifest.

**Comment by grit96** [comment]
Should we use `androidx.core.content.FileProvider` instead of `android.support.v4.content.FileProvider`?

**Comment by Relax594** [comment]
Does not make a big difference right now but looking into the future it might be a good decision to do that, yes.

**Comment by Relax594** [comment]
Thank you!

ping @chirag04 LGTM.

**Comment by chirag04** [comment]
awesome! appreciate your contributions 🙌

**Pull request merged**
