### PR TITLE
Remove RNMailTests

### PR DESCRIPTION
**Pull request by konchanSS**
#101 
I remove RNMailTests, let me know if something is wrong

### CODE REVIEW

**Comment by konchanSS** [comment]
@chirag04 can this be merge if there is no mistake?

**Comment by chirag04** [comment]
I still see some references to RNMailTests. Not sure how you removed it. want to tackle that also?

**Comment by konchanSS** [comment]
Fixed ?

**Comment by konchanSS** [comment]
@chirag04

**Comment by claudioviola** [comment]
@konchanSS and @chirag04 
Are we ready for merging this PR?

I'm getting the issue in Xcode when I try to build the app and testing react native mail on real device

Is there a way for fix the issue without waiting the merge of this PR?

Thank you!

**Comment by sfeidersullivan** [comment]
> @konchanSS and @chirag04
> Are we ready for merging this PR?
> 
> I'm getting the issue in Xcode when I try to build the app and testing react native mail on real device
> 
> Is there a way for fix the issue without waiting the merge of this PR?
> 
> Thank you!

@claudioviola
A few options in the mean time
1. Manually delete it (App -> Libraries -> RNMail.xcodeproj ->Targets -> RNMailTests -> delete)
2. Sign it with any team (App -> Libraries -> RNMail.xcodeproj ->Targets -> RNMailTests -> General -> Signing -> Team)
3. Fork it

**Comment by chirag04** [comment]
Sorry for the delay here. I'm not able to manage this project myself and would be great if somebody can help maintain the project.

**Pull request merged**
