### PR TITLE
Rebased multiple attachments

### PR DESCRIPTION
**Pull request by adamski**
Rebased #11 (the first PR for multiple attachments). Tested and working on iOS. 

#### Breaking changes
`attachment:{}` is now `attachments:[]`, e.g.:
```js
Mailer.mail({
      subject: 'My email with attachments',
      recipients: [],
      body: 'Check this out',
      isHTML: true,
      attachments: [{
        path: this.imageFilePath,  // The absolute path of the file from which to read data.
        type: 'png',   // Mime Type: jpg, png, doc, ppt, html, pdf
      },{
        path: this.audioFilePath,
        type: 'wav',   
      }]
    }, (error, event) => {
      Alert.alert(
        error,
        event,
        [
          {text: 'OK', onPress: () => console.log('OK: Email Error Response')},
        ],
        { cancelable: true }
      )
    });

```

### CODE REVIEW

**Comment by adamski** [comment]
This works with multiple image files, or image + audio files (see my other PR). Strangely initial tests with text/json files did not seem to work.

**Comment by tomislavHonig** [comment]
This is really cool feature. Will it be merged to the master?

**Comment by tomislavHonig** [comment]
And, it's not working on Android with multuple attachments. But i have fixed it, i can send you the RNMailModule.java if you want.

**Comment by adamski** [comment]
@tomislavHonig please send a PR to my [fork](https://github.com/adamski/react-native-mail/tree/multi-attachment-rebased), I will merge there and then it will appear here.

**Comment by tomislavHonig** [comment]
Thing is i am using FileProvider https://developer.android.com/reference/android/support/v4/content/FileProvider.html and you need to set this up in the androidManifest and create xml folder with provider_paths.xml file inside it. Don't know if you can do that inside the module, i think it needs to be done on application level.

**Comment by Sprit3Dan** [comment]
Any updates on this? Need this feature either.

**Comment by chirag04** [comment]
@adamski can you rebase. seems like the formatting is off.

**Comment by adamski** [comment]
@chirag04 formatting seems fine? I thought I'd fixed the indentation issue. Please link to the specific line numbers you're seeing. Also would be good to include @tomislavHonig's Android fixes too.

**Comment by adamski** [comment]
Closing, replaced with #92

**Pull request closed without merging**
