### PR TITLE
update for react native 0.40

### PR DESCRIPTION
**Pull request by avioli**
Update iOS headers to React Native 0.40 paths.

### CODE REVIEW

**Comment by chirag04** [comment]
nice. Thanks.

while you are at it can you also remove react from the header search paths in the xcode project config.

**Comment by avioli** [comment]
Just a note that this update is BREAKING, thus **highly** advisable to bump the major version, not the minor.

**Comment by avioli** [comment]
@chirag04: I've created a branch, at my fork, called [next](https://github.com/ionata/react-native-mail/tree/next) with a major version bump (3.0.0) and an updated README for the React-Native v0.40 change.

Hope it helps.

**Comment by chirag04** [comment]
merged and v3 released on npm. readme updated accordingly. 

Thanks 👍

**Pull request merged**
